douban/douban/urls.py
from django.contrib import admin
from django.urls import path
from doubanapp import views
from django.conf.urls import url,include

urlpatterns = [
    url(r'^all/', include(('doubanapp.urls'),namespace='myapp')),
]

douban/doubanapp/urls.py
from doubanapp import views
from django.conf.urls import url

app_name='[myapp]'
urlpatterns = [
    url(r'^douban/(\d*)$', views.douban,name='douban'),
    url(r'^jingdong/(\d*)$', views.jingdong,name='jingdong'),
    url(r'^weibo/(\d*)$', views.weibo,name='weibo'),
]

douban/doubanapp/models.py
from django.db import models

# Create your models here.
class db(models.Model):
    name = models.CharField(max_length=20)
    detail1 = models.CharField(max_length=200,default="")
    detail2 = models.CharField(max_length=200,default="")

class Phonedb(models.Model):
    name = models.CharField(max_length=100)
    price = models.CharField(max_length=100,default="")

class weibodb(models.Model):
    title = models.CharField(max_length=100,default="")
    hot = models.CharField(max_length=100,default="")

douban/doubanapp/views.py
from django.http import HttpResponse
from django.shortcuts import render
from doubanapp.models import db
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger
from doubanapp.models import Phonedb
from doubanapp.models import weibodb


# Create your views here.

def douban(request,current_page):
    if not current_page:
        current_page = 1
    douban_list = db.objects.all().order_by("id")    # 一定要排序
    paginator = Paginator(douban_list, 15) # 每页15条记录
    page = paginator.page(int(current_page)) # 获取第一页数据，从1开始
    context = {'page': page}
    return render(request, 'douban.html', context)

def jingdong(request,current_page):
    if not current_page:
        current_page = 1
    jingdong_list = Phonedb.objects.all().order_by("id")    # 一定要排序
    paginator = Paginator(jingdong_list, 15) # 每页5条记录
    page = paginator.page(int(current_page)) # 获取第一页数据，从1开始
    context = {'page': page}
    return render(request, 'jingdong.html', context)

    
def weibo(request,current_page):
    if not current_page:
        current_page = 1
    weibo_list = weibodb.objects.all().order_by("id")    # 一定要排序
    paginator = Paginator(weibo_list, 15) # 每页5条记录
    page = paginator.page(int(current_page)) # 获取第一页数据，从1开始
    context = {'page': page}
    return render(request, 'weibo.html', context)

douban/douban/templates/douban.html
{% load staticfiles %}
{% load pagetag %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>douban</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-sm bg-light navbar-light">
        <div class="container">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:douban' 1 %}">豆瓣</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:jingdong' 1 %}">京东</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:weibo' 1 %}">微博</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container" style="margin-top:35px;">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">id</th>
                    <th scope="col">name</th>
                    <th scope="col">director and actors</th>
                    <th scope="col">year and countries and type</th>
                </tr>
            </thead>
            {% for i in page %}
            <tr>
                <td scope="row">{{i.id}}</td>
                <td>{{i.name}}</td>
                <td>{{i.detail1}}</td>
                <td>{{i.detail2}}</td>
            </tr>
            {% endfor %}
        </table>

        <div class="row justify-content-center">
            <ul class="pagination">

                {% if page.has_previous %}
                <li class="page-item">
                    <a href="{{ page.previous_page_number }}" aria-label="Previous" class="page-link">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}
                {% for index in page.paginator.page_range %}
                    {% circle_page page.number index %}
                {% endfor %}

                {% if page.has_next %}
                <li class="page-item">
                    <a href="{{ page.next_page_number }}" aria-label="Next" class="page-link">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
    <link href="{% static 'js/jquery-3.3.1.min.js' %}" rel="stylesheet">
    <link href="{% static 'js/bootstrap.min.js' %}" rel="stylesheet">
</body>

</html>

douban/douban/templates/jingdong.html
{% load staticfiles %}
{% load pagetag %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>jingdong</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-sm bg-light navbar-light">
        <div class="container">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:douban' 1 %}">豆瓣</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:jingdong' 1 %}">京东</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:weibo' 1 %}">微博</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container" style="margin-top:35px;">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">id</th>
                    <th scope="col">name</th>
                    <th scope="col">price</th>
                </tr>
            </thead>
            {% for i in page %}
            <tr>
                <td scope="row">{{i.id}}</td>
                <td>{{i.name}}</td>
                <td>{{i.price}}</td>
            </tr>
            {% endfor %}
        </table>

        <div class="row justify-content-center">
            <ul class="pagination">

                {% if page.has_previous %}
                <li class="page-item">
                    <a href="{{ page.previous_page_number }}" aria-label="Previous" class="page-link">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}
                {% for index in page.paginator.page_range %}
                    {% circle_page page.number index %}
                {% endfor %}

                {% if page.has_next %}
                <li class="page-item">
                    <a href="{{ page.next_page_number }}" aria-label="Next" class="page-link">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
    <link href="{% static 'js/jquery-3.3.1.min.js' %}" rel="stylesheet">
    <link href="{% static 'js/bootstrap.min.js' %}" rel="stylesheet">
</body>

</html>

douban/douban/templates/weibo.html
{% load staticfiles %}
{% load pagetag %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>weibo</title>

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <nav class="navbar navbar-expand-sm bg-light navbar-light">
        <div class="container">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:douban' 1 %}">豆瓣</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:jingdong' 1 %}">京东</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'myapp:weibo' 1 %}">微博</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container" style="margin-top:35px;">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">id</th>
                    <th scope="col">title</th>
                    <th scope="col">hot</th>
                </tr>
            </thead>
            {% for i in page %}
            <tr>
                <td scope="row">{{i.id}}</td>
                <td>{{i.title}}</td>
                <td>{{i.hot}}</td>
            </tr>
            {% endfor %}
        </table>

        <div class="row justify-content-center">
            <ul class="pagination">

                {% if page.has_previous %}
                <li class="page-item">
                    <a href="{{ page.previous_page_number }}" aria-label="Previous" class="page-link">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}
                {% for index in page.paginator.page_range %}
                    {% circle_page page.number index %}
                {% endfor %}

                {% if page.has_next %}
                <li class="page-item">
                    <a href="{{ page.next_page_number }}" aria-label="Next" class="page-link">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
    <link href="{% static 'js/jquery-3.3.1.min.js' %}" rel="stylesheet">
    <link href="{% static 'js/bootstrap.min.js' %}" rel="stylesheet">
</body>

</html>